### ISSUE TITLE
redirectPrintToLogger property triggering redirection of prints to loggers for the (default) "false" value.

### ISSUE THREAD

**Issue by david-coultous** [pysys-test/pysys-test#36]
**Describe the bug**
The check against the redirectPrintToLogger property in baserunner.py incorrectly assume boolean type
This is at line 418:-

```
if getattr(self.project, 'redirectPrintToLogger', False):
			sys.stdout = PySysPrintRedirector()
```
As this property has a string type, the behaviour is not as expected.

**To Reproduce**
By default this property is provided as 

`<property name="redirectPrintToLogger" value="false"/>`

in the pysysproject.xml file. This (or "true" for that matter) would be seen as True by this if statement, and lead to prints being redirected to the log file.

**Expected behavior**
From other property handing it would appear the correct course would be to check the value of this property against "true" or "false". Thus a value of "false" would then correctly not lead to `sys.stdout` being set to `PySysPrintRedirector()`

**Affected version(s)**
- Python version(s): 3.7.5
- PySys version(s): 1.5.1
- Operating System(s): Ubuntu.

**Comment by ben-spiller** [comment]
Thanks for the bug report. This is fixed in "master" and will be included in the 1.6.0 release in a few days :)

**Comment by david-coultous** [comment]
This has been updated to :-

```
if getattr(self.project, 'redirectPrintToLogger', True):
			sys.stdout = PySysPrintRedirector()
```
in v1.6.0 (and 1.6.1), which suffers the same problem, except there is now no way of turning off this feature. So the bug is not fixed but worsened....

**Comment by david-coultous** [comment]
my bad :-)
